### ISSUE TITLE
mongodb.config

### ISSUE THREAD

**Issue by gunar** [icflorescu/openshift-cartridge-mongodb#14]
Hi, where can I find the mongodb.config file?

There's one in `/var/mongodb.conf` but I can't edit it (permission denied, can't sudo).

I'd like to add `smallfiles=true` and `noprealloc=true` to preserve disk space in my gear.

Thank you!!

**Comment by icflorescu** [comment]
Hi Gunar,

There's no `mongodb.conf` associated with the cartridge MongoDB instance (`/var/mongodb.conf` belongs to OpenShift, as you noticed we can't touch it and has nothing to do with us :-).

I'm using command line parameters to start `mongod` - have a look at `bin/control` [here](https://github.com/icflorescu/openshift-cartridge-mongodb/blob/master/bin/control#L18).

There's no need to use `noprealloc`, since this **is the default behavior** since MongoDB 2.6 (and the config option itself has actually been deprecated).

About `smallfiles=true` - I thought about including the option in the control script, but it does impact performance and since many people are using this cartridge to add a distinct MongoDB instance to an existing application instance, space isn't an issue (each gear has its own quota).

---

But if you really want to change the default options you can do so by logging in with `ssh` into your application gear and editing the control script directly. Once you've logged in, you can do:

```
nano mongodb/bin/control
```

...and add `smallfiles=true` to `function start() {`. Just make sure to add it **after** `--nounixsocket`.

---

I'll admit this is not really straightforward, but I haven't been able to come up with an easy way to make the settings customizable. If you have a better solution please feel free to let me know.

**Comment by icflorescu** [comment]
Also, don't forget to restart the cartridge afterwards.

Since other people may run into the same issue, I've added this into the README.md - FAQ.

Thanks for bringing it to my attention and let me know if I can close the issue :-)

**Comment by gunar** [comment]
I understand. Thank you very much for your thorough answer.
I've edited the command line parameters. Let's see how it rolls.

BTW, you're awesome :)

**Comment by icflorescu** [comment]
Thanks for the kind words :-)
