### ISSUE TITLE
How install mongo shell? 

### ISSUE THREAD

**Issue by Pavel-Evdokimov** [icflorescu/openshift-cartridge-mongodb#9]
Hello! I need use mongo shell in my app. How can I install it? Thanks!

**Comment by azariah001** [comment]
Would also like to know. I need to be able to secure the server and add a user which I cannot do through the config files because they're at the filesystem root of Openshift which is secured for reasons. :disappointed:

**Comment by icflorescu** [comment]
This cartridge doesn't install `mongo` shell in order to save space. See notes on the README and the discussion on issue #1.

You can use `rhc port-forward` and `mongo` shell to securely connect from your local development machine; see [OpenShift docs](https://developers.openshift.com/en/managing-port-forwarding.html).

Or, if you **really** need `mongo` on the server cartridge, you could fork this repository and modify [the install script](https://github.com/icflorescu/openshift-cartridge-mongodb/blob/master/bin/install) to keep it (you might need to also keep some dependencies, I'm not sure), but you'll lose a lot of space...

**Comment by myknbani** [comment]
I dunno what I'm doing wrong, but the port-forward shell just closes with the following error:

~/.gem/ruby/2.2.0/gems/net-ssh-2.9.2/lib/net/ssh/ruby_compat.rb:30:in `select': closed stream (IOError)

And getting this error using `mongo --port 49226`

```
[thread1] Error: network error while attempting to run command 'isMaster' on host '127.0.0.1:49226'  :
```

It shows the following on the port-forward shell:

`mongodb 127.0.0.1:49226  =>  [my domain].rhcloud.com:49226`
